/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleHistoryItem: typeof import('./src/components/TitleBar/History/ArticleHistoryItem.vue')['default']
    Bangumi: typeof import('./src/components/Bangumi/Bangumi.vue')['default']
    BangumiHot: typeof import('./src/components/Bangumi/BangumiHot.vue')['default']
    BangumiItem: typeof import('./src/components/Home/Bangumi/BangumiItem.vue')['default']
    BangumiProgress: typeof import('./src/components/Bangumi/BangumiProgress/BangumiProgress.vue')['default']
    BangumiProgressItem: typeof import('./src/components/Bangumi/BangumiProgress/BangumiProgressItem.vue')['default']
    BangumiSchedule: typeof import('./src/components/Bangumi/BangumiSchedule/BangumiSchedule.vue')['default']
    BangumiScheduleItem: typeof import('./src/components/Bangumi/BangumiSchedule/BangumiScheduleItem.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Bottom: typeof import('./src/components/public/Bottom.vue')['default']
    Carousel: typeof import('./src/components/public/Carousel.vue')['default']
    CommonView: typeof import('./src/components/Home/CommonView/CommonView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HistoryInfoItem: typeof import('./src/components/TitleBar/History/HistoryInfoItem.vue')['default']
    LiveHistoryItem: typeof import('./src/components/TitleBar/History/LiveHistoryItem.vue')['default']
    LiveItem: typeof import('./src/components/public/LiveItem.vue')['default']
    LiveStreamItem: typeof import('./src/components/TitleBar/Updates/LiveStreamItem.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RankingItem: typeof import('./src/components/Home/SectionItem/RankingItem.vue')['default']
    RecommendRow: typeof import('./src/components/Bangumi/BangumiRecommendRow/RecommendRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionItem: typeof import('./src/components/Home/SectionItem/SectionItem.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar/TitleBar.vue')['default']
    TruncatedText: typeof import('./src/components/public/TruncatedText.vue')['default']
    UpdatesItem: typeof import('./src/components/TitleBar/Updates/UpdatesItem.vue')['default']
    VideoHistoryItem: typeof import('./src/components/TitleBar/History/VideoHistoryItem.vue')['default']
    VideoItem: typeof import('./src/components/public/VideoItem.vue')['default']
  }
}
